esphome:
  name: $name
  on_boot:
    priority: 200
    then:
      - wait_until:
          condition:
            wifi.connected:
          timeout: 15s

esp32:
  board: ${board_type} #az-delivery-devkit-v4  # nodemcu-32s / esp-wrover-kit
  framework:
    type: esp-idf  # arduino / esp-idf — not ready missing json and async_tcp
    version: recommended  # latest
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: y
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"
      CONFIG_TASK_WDT: "y"  # prevents watchdog timeouts
      CONFIG_TASK_WDT_TIMEOUT_S: "30"  # prevents watchdog timeouts
      CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0: "n"  # prevents watchdog timeouts
      CONFIG_LOG_DEFAULT_LEVEL: "0"  # prevents "ESP-IDF" Guru Meditation Error
      CONFIG_FREERTOS_HZ: "1000"

psram:

preferences:
  flash_write_interval: 60min

# Enable logging
logger:
  level: DEBUG  # NONE / ERROR / INFO / DEBUG / VERBOSE
  # baud_rate: 0  # to disable logging via UART
  logs:
    text_sensor: ERROR
    homeassistant.sensor: ERROR
    canbus: ERROR  # setting log level for canbus lower than INFO may crash  : esphome/issues#4051
    uptime: ERROR
    uptime.sensor: ERROR
    wifi_signal: ERROR
    wifi_signal.sensor: ERROR
    esp32.preferences: ERROR
    internal_temperature: ERROR
    esp-idf: ERROR
    select: ERROR
    number: ERROR
    sensor: INFO
    tt: INFO  # DEBUG for crc reverse engineering

# Enable Home Assistant API
api:
  reboot_timeout: 30min

ota:
  - platform: esphome

safe_mode:
