# for flashing : press boot button for 2-3 seconds before the serial connection initialize
# After OTA update, the EN (reset) button must be pressed to run firmware
# do not use gpio12 (MTDI)

substitutions:
  name: canbus
  friendly_name: "CanBus Controller"

  ### canbus
  can_tx_pin: "GPIO22"  # GPIO5
  can_rx_pin: "GPIO21"  # GPIO4
  
  ### board
  board_type: az-delivery-devkit-v4 #nodemcu-32s #esp-wrover-kit
  
  ### time
  TZ: "Europe/Zurich"  # timezone

toptronic:
  - id: tt_HV  # HomeVent
    canbus_id: cbus  # the canbus bit_rate must be 50kbps
    device_type: HV  # WEZ, HV, BM (BD is an alias for BM and BM must be used)
    device_addr: 8  # defaults are : HV=8, BM=8, WEZ=1
    language: en  # de, en, fr, it

  - id: tt_BM  # display
    canbus_id: cbus  # the canbus bit_rate must be 50kbps
    device_type: BM
    device_addr: 8
    language: en

external_components:
  - source:
      type: local
      path: components

packages:
  wifi: !include src/wifi.yaml
  board: !include src/board.yaml
  time: !include src/time.yaml
  canbus: !include src/canbus.yaml
  sensors_others: !include src/sensors_others.yaml
  switch: !include src/switch.yaml
  # debug: !include src/debug.yaml

# web_server:
#   port: 80
#   log: false
